# Generated by Django 4.0.6 on 2022-07-11 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blogpost_exception_alter_blogpost_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='exception',
            new_name='exceprtion',
        ),
    ]
