# Generated by Django 4.0.6 on 2022-07-17 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blogpost_coverimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='exceprtion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='topic',
            field=models.CharField(max_length=50),
        ),
    ]
